# docker/Dockerfile
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo requirements.txt desde la carpeta docker
COPY docker/requirements.txt .

# Instala las dependencias
RUN pip install -r requirements.txt

# Copia el código fuente desde la carpeta server
COPY server /app

# Expón el puerto 5000
EXPOSE 5000

# Ejecuta el servidor Flask
CMD ["python", "app.py"]