version: '3.8'

services:
  python:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: python_flask_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ../src/html:/usr/share/nginx/html
      - ../config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_DB: salud-y-bienestar_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
